# Generated by Django 4.0.4 on 2022-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('passport_number', models.CharField(default='', max_length=500)),
                ('date_of_birth', models.DateField(default='2015-12-12')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.IntegerField(blank=True, default='0123430000')),
                ('brief_description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
