# Generated by Django 4.0.4 on 2022-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vwired', '0002_alter_contact_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
